name: Assign new issues to specific user
on:
  issues:
    types: [opened]
permissions:
  issues: write 
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign user
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ rachelj3 }}
